name: Node.js CI
on: [push, pull_request, fork, pull_request_review]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i
      - run: npx playwright install --with-deps
      - run: pnpm build
      - run: pnpm run typecheck
      - run: pnpm run test
        env:
          CI: true
